name: campaign
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  custom_pop_up_menu: 1.1.0
  date_time_format: 1.1.0
  dotted_border: 1.0.6
  dotted_line: 2.0.2
  equatable: 1.2.5
  flutter_screenutil: 3.2.0
  flutter_svg: 0.19.1
  font_awesome_flutter: 8.10.0
  http: 0.12.2
  kumi_popup_window: 1.0.10
  percent_indicator: 2.1.8
  pie_chart: 4.0.1
  provider: 4.3.2+2
  share: 0.6.5+4
  smooth_page_indicator: 0.2.0
  scrollable_positioned_list: 0.1.8

  jumping_bottom_nav_bar:
    path: ./lib/CustomPlugins/jumping_bottom_nav_bar

  status_alert:
    path: ./lib/CustomPlugins/status_alert

  keicy_text_form_field:
    git: https://github.com/FlutterDev6778/keicy_text_form_field.git

  keicy_raised_button:
    git: https://github.com/FlutterDev6778/keicy_raised_button.git

  keicy_network_image:
    git: https://github.com/FlutterDev6778/keicy_network_image.git

  keicy_avatar_image:
    git: https://github.com/FlutterDev6778/keicy_avatar_image.git

  keicy_progress_dialog:
    git: https://github.com/FlutterDev6778/keicy_progress_dialog.git

  keicy_rating_bar:
    git: https://github.com/FlutterDev6778/keicy_rating_bar.git

  keicy_utils:
    git: https://github.com/FlutterDev6778/keicy_utils.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/Assets/Images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir-Black
      fonts:
        - asset: lib/Assets/Fonts/Avenir-Black.ttf

    - family: Avenir-BlackOblique
      fonts:
        - asset: lib/Assets/Fonts/Avenir-BlackOblique.ttf

    - family: Avenir-Book
      fonts:
        - asset: lib/Assets/Fonts/Avenir-Book.ttf

    - family: Avenir-BookOblique
      fonts:
        - asset: lib/Assets/Fonts/Avenir-BookOblique.ttf

    - family: Avenir-Heavy
      fonts:
        - asset: lib/Assets/Fonts/Avenir-Heavy.ttf

    - family: Avenir-HeavyOblique
      fonts:
        - asset: lib/Assets/Fonts/Avenir-HeavyOblique.ttf

    - family: Avenir-Light
      fonts:
        - asset: lib/Assets/Fonts/Avenir-Light.ttf

    - family: Avenir-LightOblique
      fonts:
        - asset: lib/Assets/Fonts/Avenir-LightOblique.ttf

    - family: Avenir-Medium
      fonts:
        - asset: lib/Assets/Fonts/Avenir-Medium.ttf

    - family: Avenir-MediumOblique
      fonts:
        - asset: lib/Assets/Fonts/Avenir-MediumOblique.ttf

    - family: Avenir-Oblique
      fonts:
        - asset: lib/Assets/Fonts/Avenir-Oblique.ttf

    - family: Avenir-Roman
      fonts:
        - asset: lib/Assets/Fonts/Avenir-Roman.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
